### ISSUE TITLE
Infografia-Sandra

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-SANDRAVELASCO#1]
[INTRODUCCIÓN A LA GESTIÓN DE PROYECTOS (1).pdf](https://github.com/user-attachments/files/16752982/INTRODUCCION.A.LA.GESTION.DE.PROYECTOS.1.pdf)

**Comment by saul19bautista** [comment]
BUENTRABAJO 
19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
